In [29]:
import numpy as np
import matplotlib.pyplot as plt
my_img = plt.imread('Train/1.jpg')
ImagesArray=np.ones([2400, 784])
onesArray=np.ones([2400, 1])

print("Assigning Targets")
c0=(np.ones((2400,1)))

c1=(np.ones((2400,1)))
c2=(np.ones((2400,1)))
c3=(np.ones((2400,1)))
c4=(np.ones((2400,1)))
c5=(np.ones((2400,1)))
c6=(np.ones((2400,1)))
c7=(np.ones((2400,1)))
c8=(np.ones((2400,1)))
c9=(np.ones((2400,1)))




for i in range(0,len(c0)):
    if not(i>=0 and i<=240):
        c0[i]=-1;
        
for i in range(0,len(c1)):
    if not(i>240 and i<=240*2):
        c1[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*2 and i<=240*3):
        c2[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*3 and i<=240*4):
        c3[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*4 and i<=240*5):
        c4[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*5 and i<=240*6):
        c5[i]=-1;
        
        
for i in range(0,len(c1)):
    if not(i>240*6 and i<=240*7):
        c6[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*7 and i<=240*8):
        c7[i]=-1;
        
for i in range(0,len(c1)):
    if not(i>240*8 and i<=240*9):
        c8[i]=-1;
for i in range(0,len(c1)):
    if not(i>240*9 and i<=240*100):
        c9[i]=-1;




print("Importing Images")

for i in range (0,2400):
    Image=plt.imread('Train/'+str(i+1)+'.jpg')
    Image =Image.flatten()
    #print(Image)
    #print(len(Image))
    #print(ImagesArray.shape)
    ImagesArray[i]=Image
ImagesArray=np.append(ImagesArray, onesArray, axis=1)
print(ImagesArray[0][784])
print(len(ImagesArray))     
x=np.asmatrix(ImagesArray)  
#print(x[0])
xtranspose=ImagesArray.transpose()
#print(np.info(xtranspose))
#print(np.info(x))
print("X * Transpose")

mult=np.dot(xtranspose, x)
#print(np.info(mult))
inverse=np.linalg.pinv(mult)
#print(np.info(inverse))
print("Factor")

Factor=np.dot(inverse,xtranspose)

print("Weight Vectors")


w0=np.dot(Factor,c0)
print(w0.shape)
w1=np.dot(Factor,c1)
w2=np.dot(Factor,c2)
w3=np.dot(Factor,c3)
w4=np.dot(Factor,c4)
w5=np.dot(Factor,c5)
w6=np.dot(Factor,c6)

w7=np.dot(Factor,c7)
w8=np.dot(Factor,c8)
w9=np.dot(Factor,c9)
#print(w9)
weights=[w0,w1,w2,w3,w4,w5,w6,w7,w8,w9]
print("Testing phase")
testArray=np.ones([200, 784])
onesArray=np.ones([200, 1])

#print(testArray)
for i in range (0,200):
    Image=plt.imread('test/'+str(i+1)+'.jpg')
    Image= np.asmatrix(Image)
    Image =Image.flatten()
    testArray[i]=Image

testArray=np.append(testArray, onesArray, axis=1)

confusion_matrix=np.zeros((10, 10))
print(confusion_matrix)
for i in range(0,200):
    image0=testArray[i]
    #print(image0[0])
    output=np.dot(weights[0].transpose(),image0)
    #output=output[0][0]
    #print(output[0].shape)
    c=0;
    for j in range(0,len(weights)):
        output2=np.dot(weights[j].transpose(),image0)
        #print(output2.shape)
        if output2>output:
            output=output2;
            #print("Here")
            c=j
    if i in range(0, 20):
            #print(i)
            confusion_matrix[0][c]+=1
    if i in range(20, 40):
            confusion_matrix[1][c]+=1
    if i in range(40, 60):
            confusion_matrix[2][c]+=1
    if i in range(60, 80):
            confusion_matrix[3][c]+=1
    if i in range(80, 100):
            confusion_matrix[4][c]+=1
    if i in range(100, 120):
            confusion_matrix[5][c]+=1
    if i in range(120, 140):
            confusion_matrix[6][c]+=1
    if i in range(140, 160):
            confusion_matrix[7][c]+=1
    if i in range(160, 180):
            confusion_matrix[8][c]+=1
    if i in range(180, 200):
            confusion_matrix[9][c]+=1
    #print(c)
Accuracy=0.0;
for i in range (0,10):
    Accuracy+=confusion_matrix[i][i]
print("the Accuracy is "+str(Accuracy/200*100))
    
print(confusion_matrix)

matrix_image=np.zeros(np.array(confusion_matrix.shape) * 100)

for j in range(confusion_matrix.shape[0]):
    for k in range(confusion_matrix.shape[1]):
        matrix_image[j * 100: (j+1) * 100, k * 100: (k+1) * 100] = confusion_matrix[j, k]

plt.imsave( './Confusion.jpg' , matrix_image)


Assigning Targets
Importing Images
1.0
2400
X * Transpose
Factor
Weight Vectors
(785, 1)
Testing phase
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
the Accuracy is 79.0
[[19.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  3. 11.  2.  2.  1.  0.  0.  0.  0.]
 [ 0.  0.  1. 16.  0.  1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0. 17.  1.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  0. 14.  1.  0.  2.  2.]
 [ 0.  0.  0.  0.  0.  0. 20.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  0. 15.  0.  3.]
 [ 0.  0.  1.  0.  0.  3.  0.  0. 15.  1.]
 [ 1.  0.  0.  1.  2.  1.  0.  4.  0. 11.]]
